"""create model token

Revision ID: 2ca7c8df6fe6
Revises: 743d4c954fd0
Create Date: 2022-08-25 07:24:54.058518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca7c8df6fe6'
down_revision = '743d4c954fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_number', sa.Integer(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_number'], ['employees.staff_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
