"""added cascade delete in department, employees, roles

Revision ID: 63b047938682
Revises: 5fa2802975b1
Create Date: 2022-08-16 21:46:10.442835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b047938682'
down_revision = '5fa2802975b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_role_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_role_id_fkey', 'employees', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
