"""create model account

Revision ID: 743d4c954fd0
Revises: ef886c99ab6a
Create Date: 2022-08-24 00:24:37.174621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743d4c954fd0'
down_revision = 'ef886c99ab6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('login', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('staff_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_number'], ['employees.staff_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
