"""Added Office.country

Revision ID: ce47fbcd066d
Revises: ade33a921656
Create Date: 2022-08-08 11:07:07.685547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce47fbcd066d'
down_revision = 'ade33a921656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('country', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offices', 'country')
    # ### end Alembic commands ###
